version: "3.5"
services:
  web:
    build:
      context: ./web-view
      dockerfile: Dockerfile
      target: development
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - bridge-network
    command: sh -c "npm run build && npm run dev"

  social_api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    command: sh -c "npm run start:dev"
    ports:
      - "127.0.0.1:3001:3000"
    restart: always
    networks:
      - bridge-network
    depends_on:
      - redis
      - social_mongodb

  social_nodejs_api:
    build:
      context: ./nodejs_api
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    ports:
      - "127.0.0.1:3002:3000"
    restart: always
    networks:
      - bridge-network
    depends_on:
      - redis
      - social_mongodb

  social_mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    command: mongod --auth
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=social_network
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      # seeding scripts
      # named volumes
      - ./database/mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database/mongodb:/data/db
      - ./database/mongoconfig:/data/configdb
    networks:
      - bridge-network

  redis:
    container_name: app_redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
